import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import {Toaster} from "react-hot-toast";
import App from "./App";



const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <App>
        <Providers>
        {children}
        </Providers>
        </App>

        <Toaster position="top-center" reverseOrder={false}/>
        
        </body>
       
    </html>
  );
}
